target-applies-to-host = false

[host]
rustflags = [
    "--cfg", "anodized_print",
    "--cfg", "anodized_panic",
    "--cfg", "anodized_try",
]

[target.aarch64-apple-darwin]
rustflags = [
    "--cfg", "anodized_print",
    "--cfg", "anodized_panic",
    "--cfg", "anodized_try",
]
